### ISSUE TITLE
Setup problem

### ISSUE THREAD

**Issue by ivopintodasilva** [creaktive/KeyLab_Essential_Hacks#2]
First of all, thanks a lot for the effort put into this!

I just got a Essential 49 and was browsing the web for a solution like this, it brings so much value to my workflow with this controller 🙏

However, I was not able to get the setup right and couldn't get the knobs to control the devices 😢

- What device template should the Keylab be in order for this hack to work? When I put it in DAW mode, the command center stops working and the knobs do not trigger any change on the armed device...

I even tried changing my control surface to channels 1 and 2 (like you have on your screenshot), and even then I couldn't get it to work.

Can you point somewhere where I could look to troubleshoot this problem?

Once again, thank you very much for this! 😃

**Comment by creaktive** [comment]
Hi! Sorry for the delay... Unfortunately, my solution is kind of unstable; I myself often struggle with getting it right. Technically, mapping the encoders onto a separate channel is a much better idea (albeit slightly less convenient). I recommend you to check https://drolez.com/blog/music/arturia-keylab-ableton-setup.php
